# ======================
# Puntos de Entrada
# ======================
entryPoints:
  webinsecure:
    address: ":80"  # Punto de entrada HTTP (sin SSL)

# ======================
# Configuración del API
# ======================
api:
  dashboard: true  # Habilita el dashboard
  insecure: true   # Solo para desarrollo (en producción usar autenticación)

# ======================
# Proveedores
# ======================
providers:
  docker:
    exposedByDefault: false  # Seguridad: no exponer todos los contenedores
    network: "traefik_network"  # Red específica para descubrimiento

# ======================
# Métricas (Prometheus)
# ======================
metrics:
  prometheus:
    entryPoint: "webinsecure"  # Punto de entrada para métricas
    addServicesLabels: true  # Añade etiquetas de servicio a las métricas
